# Generated by Django 2.2.6 on 2019-10-26 23:30

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('funding_total', models.DecimalField(decimal_places=9, max_digits=20)),
                ('status', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('us_state', localflavor.us.models.USStateField(max_length=2)),
                ('us_city', models.CharField(max_length=200)),
                ('funding_rounds', models.IntegerField()),
                ('number_of_investors', models.IntegerField()),
                ('acquirer', models.CharField(blank=True, max_length=200, null=True)),
                ('acquirer_category', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirer_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('acquirer_us_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('acquirer_us_city', models.CharField(blank=True, max_length=200, null=True)),
                ('acquired_price', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('acquired_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('county', models.CharField(max_length=100)),
                ('founded_at', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Company')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Investor')),
            ],
        ),
    ]
